### ISSUE TITLE
Error when upgrading templates from TKG+ 1.17 to TKG+ 1.18 

### ISSUE THREAD

**Issue by dmbuil** [vmware/container-service-extension#1107]
There is an issue when upgrading TKG+ 1.17 templates (CSE2.6.1-compatible) to TKG+ 1.18 templates (CSE3.0.2-compatible).  

I let the template be “ubuntu-16.04_tkg-1.17_weave-2.5.2_rev1” instead of “ubuntu-16.04_tkgplus-1.17_weave-2.5.2_rev1”, as per CSE2.6.1 `template.yaml` legacy naming convention; template contents (scripts, k8s versions, etc.) are the same than CSE3.0.2's, so no further issues to be expected. 
The “upgrade_from” field was set to the upgrade tree consequently.
 
Nevertheless, when it comes to test the upgrade process from “tkg-1.17” to “tkgplus-1.18”, the process fails:
 
![img01](https://user-images.githubusercontent.com/22377986/125253487-c1bc2880-e2f9-11eb-9659-f4c7c6f6ffb4.jpg)
 
After some investigation, we’ve been told that the template’s name is indeed very important, as it is used by CSE altogether with other params (“k8s_version”, “cni_version”, etc.) to determine what kind of software is installed within.

The `template.yaml` excerpt for the tkg-1.17 template:

```yaml
-
    kind: TKG+
    compute_policy: ""
    cpu: 2
    deprecated: false
    description: "Ubuntu 16.04, Docker-CE 18.09.7, (Tanzu Kubernetes Grid) Kubernetes 1.17.3, Weave 2.5.2"
    mem: 2048
    name: ubuntu-16.04_tkg-1.17_weave-2.5.2
    revision: 1
    sha256_ova: 3c1bec8e2770af5b9b0462e20b7b24633666feedff43c099a6fb1330fcc869a9
    source_ova: https://cloud-images.ubuntu.com/releases/xenial/release-20180418/ubuntu-16.04-server-cloudimg-amd64.ova
    source_ova_name: ubuntu-16.04-server-cloudimg-amd64.ova
    os: "ubuntu-16.04"
    docker_version: "18.09.7"
    kubernetes: "Tanzu Kubernetes Grid"
    kubernetes_version: "1.17.3"
    cni: "weave"
    cni_version: "2.5.2"
    upgrade_from:
       - ""
```
