### ISSUE TITLE
Kubernetes || CSE installation issue

### ISSUE THREAD

**Issue by ManivelRR** [vmware/container-service-extension#311]
Hi All,

 

Im new to CSE K8s.While installating CSE on photon OS,im getting the below error.Please suggest.

 root@photon-machine [ ~ ]# cse version
CSE, Container Service Extension for VMware vCloud Director, version 1.2.7
root@photon-machine [ ~ ]#

 

root@photon-machine [ ~ ]# cse install --config config.yaml

Traceback (most recent call last):

  File "/usr/bin/cse", line 10, in <module>

    sys.exit(cli())

  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__

    return self.main(*args, **kwargs)

  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main

    rv = self.invoke(ctx)

  File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke

    return callback(*args, **kwargs)

  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func

    return f(get_current_context(), *args, **kwargs)

  File "/usr/lib/python3.6/site-packages/container_service_extension/cse.py", line 239, in install

    ext_install=ext_install)

  File "/usr/lib/python3.6/site-packages/container_service_extension/configure_cse.py", line 644, in install_cse

    config = get_validated_config(config_file_name)

  File "/usr/lib/python3.6/site-packages/container_service_extension/configure_cse.py", line 328, in get_validated_config

    config = yaml.safe_load(config_file)

  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 162, in safe_load

    return load(stream, SafeLoader)

  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load

    return loader.get_single_data()

  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 41, in get_single_data

    node = self.get_single_node()

  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node

    document = self.compose_document()

  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document

    node = self.compose_node(None, None)

  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node

    node = self.compose_mapping_node(anchor)

  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node

    while not self.check_event(MappingEndEvent):

  File "/usr/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event

    self.current_event = self.state()

  File "/usr/lib/python3.6/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key

    "expected <block end>, but found %r" % token.id, token.start_mark)

yaml.parser.ParserError: while parsing a block mapping

  in "config.yaml", line 1, column 1

expected <block end>, but found '-'

  in "config.yaml", line 87, column 1

root@photon-machine [ ~ ]#

**Comment by andrew-ni** [comment]
Seems like the error is that config.yaml is not valid yaml. Can you verify that your config file is fine (maybe with a yaml parser or `cse check --config config.yaml`). If the problem persists, can you attach your config file (redacted) here?

**Comment by ManivelRR** [comment]
> Seems like the error is that config.yaml is not valid yaml. Can you verify that your config file is fine (maybe with a yaml parser or `cse check --config config.yaml`). If the problem persists, can you attach your config file (redacted) here?

Hi Andrew,

root@photon-machine [ ~ ]# cse check --config config.yaml
Traceback (most recent call last):
  File "/usr/bin/cse", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 716, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/python3.6/site-packages/click/core.py", line 641, in make_conte                                                                                        xt
    self.parse_args(ctx, args)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1089, in parse_arg                                                                                        s
    rest = Command.parse_args(self, ctx, args)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1476, in handle_pa                                                                                        rse_result
    value = invoke_param_callback(
NameError: name 'invoke_param_callback' is not defined
root@photon-machine [ ~ ]#

My YAML config file

---
amqp:
  exchange: cse-ext
  host: 10.128.7.36
  password: Password@1234
  port: 5672
  prefix: vcd
  routing_key: cse
  ssl: false
  ssl_accept_all: false
  username: uladmin
  vhost: /

vcd:
  api_version: '29.0'
  host: 10.128.7.18
  log: true
  password: Password@1234
  port: 443
  username: administrator
  verify: false

vcs:
- name: 10.128.7.21
  password: Password@1234
  username: cseadmin@vsphere.local
  verify: false

service:
  enforce_authorization: false
  listeners: 5

broker:
  catalog: cse
  cse_msg_dir: /tmp/cse
  default_template: photon-v2
  ip_allocation_mode: pool
  network: ManivelDV
  org: CSE
  storage_profile: '*'
  templates:
  - admin_password: Password@1234
    catalog_item: photon-custom-hw11-2.0-304b817-k8s
  cleanup: true
    cpu: 2
    description: 'PhotonOS v2

      Docker 17.06.0-4

      Kubernetes 1.9.1

      weave 2.3.0'
    mem: 2048
    name: photon-v2
    sha256_ova: cb51e4b6d899c3588f961e73282709a0d054bb421787e140a1d80c24d4fd89e1
    source_ova: http://dl.bintray.com/vmware/photon/2.0/GA/ova/photon-custom-hw11-2.0-304b817.ova
    source_ova_name: photon-custom-hw11-2.0-304b817.ova
    temp_vapp: photon2-temp
  - admin_password: Password@1234
    catalog_item: ubuntu-16.04-server-cloudimg-amd64-k8s
    cleanup: true
    cpu: 2
    description: 'Ubuntu 16.04

      Docker 18.03.0~ce

      Kubernetes 1.10.1

      weave 2.3.0'
    mem: 2048
    name: ubuntu-16.04
    sha256_ova: 3c1bec8e2770af5b9b0462e20b7b24633666feedff43c099a6fb1330fcc869a9
    source_ova: https://cloud-images.ubuntu.com/releases/xenial/release-20180418/ubuntu-16.04-server-cloudimg-amd64.ova
    source_ova_name: ubuntu-16.04-server-cloudimg-amd64.ova
    temp_vapp: ubuntu1604-temp
  type: default
  vdc: CSE
---

when i check my YAML file with http://www.yamllint.com/, it says it is valid.

Thanks,
Manivel R

**Comment by andrew-ni** [comment]
Hi, can you provide a pip list/freeze (`pip list` or `pip freeze`)

Also, can you edit your previous post to include the config.yaml in a code block (surround the text content with backticks and 'yaml like this:

\`\`\`yaml
my config content pasted
\`\`\`

**Comment by ManivelRR** [comment]
Hi Andrew,

Thanks for the reply.Please find the details of pip list,pip freeze and config.yaml file.

Thanks,
Manivel R
[CSE.txt](https://github.com/vmware/container-service-extension/files/3124050/CSE.txt)

**Comment by andrew-ni** [comment]
I used http://www.yamllint.com/ and copy/pasted your config file, and it seems that the config file is invalid yaml. The key 'mem' was indented out by one level. Make sure your config file looks exactly like this:

```yaml
amqp:
  exchange: cse-ext
  host: 10.128.7.36
  password: Password@1234
  port: 5672
  prefix: vcd
  routing_key: cse
  ssl: false
  ssl_accept_all: false
  username: uladmin
  vhost: /

vcd:
  api_version: '29.0'
  host: 10.128.7.18
  log: true
  password: Password@1234
  port: 443
  username: administrator
  verify: false

vcs:
- name:  10.128.7.21
  password: Password@1234
  username: cseadmin@vsphere.local
  verify: false

service:
  enforce_authorization: false
  listeners: 5

broker:
  catalog: cse
  cse_msg_dir: /tmp/cse
  default_template: photon-v2
  ip_allocation_mode: pool
  network: ManivelDV
  org: CSE
  storage_profile: '*'
  templates:
  - admin_password: Password@1234
    catalog_item: photon-custom-hw11-2.0-304b817-k8s
    cleanup: true
    cpu: 2
    description: 'PhotonOS v2

      Docker 17.06.0-4

      Kubernetes 1.9.1

      weave 2.3.0'
    mem: 2048
    name: photon-v2
    sha256_ova: cb51e4b6d899c3588f961e73282709a0d054bb421787e140a1d80c24d4fd89e1
    source_ova: http://dl.bintray.com/vmware/photon/2.0/GA/ova/photon-custom-hw11-2.0-304b817.ova
    source_ova_name: photon-custom-hw11-2.0-304b817.ova
    temp_vapp: photon2-temp
  - admin_password: Password@1234
    catalog_item: ubuntu-16.04-server-cloudimg-amd64-k8s
    cleanup: true
    cpu: 2
    description: 'Ubuntu 16.04

      Docker 18.03.0~ce

      Kubernetes 1.10.1

      weave 2.3.0'
    mem: 2048
    name: ubuntu-16.04
    sha256_ova: 3c1bec8e2770af5b9b0462e20b7b24633666feedff43c099a6fb1330fcc869a9
    source_ova: https://cloud-images.ubuntu.com/releases/xenial/release-20180418/ubuntu-16.04-server-cloudimg-amd64.ova
    source_ova_name: ubuntu-16.04-server-cloudimg-amd64.ova
    temp_vapp: ubuntu1604-temp
  type: default
  vdc: CSE
```
